# Generated by Django 5.0.4 on 2024-04-09 03:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=64)),
                ('CPF_CNPJ', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateTimeField(default=datetime.datetime(2024, 5, 9, 0, 25, 11, 247998))),
                ('data_de_emprestimo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GerentePJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome_completo', models.CharField(max_length=64)),
                ('empresa_atendida', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCompraEVendaAcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprador', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=64)),
                ('nome_acao', models.CharField(max_length=64)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoTransferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recebeu', models.CharField(max_length=64)),
                ('tipo_recebe', models.CharField(max_length=64)),
                ('enviou', models.CharField(max_length=64)),
                ('tipo_envia', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GerentePF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome_completo', models.CharField(max_length=64)),
                ('agencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtb.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('CPF', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=8)),
                ('saldo_da_conta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('CNPJ', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome_da_empresa', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=8)),
                ('setor', models.CharField(max_length=64)),
                ('saldo_da_conta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
