# Generated by Django 5.0.4 on 2024-04-09 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0002_agencia_emprestimo_gerentepj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 11, 45, 59, 505950)),
        ),
    ]
