# Generated by Django 5.0.4 on 2024-04-10 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0003_alter_emprestimo_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 22, 7, 33, 602281)),
        ),
    ]
