# Generated by Django 5.0.4 on 2024-04-10 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0007_remove_historicocompraevendaacoes_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 0, 12, 39, 798278)),
        ),
    ]
