# Generated by Django 5.0.4 on 2024-04-10 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0009_rename_useracoes_pessoafisica_user_acoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 0, 34, 22, 896278)),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='saldo_da_conta',
            field=models.FloatField(default=0),
        ),
    ]
