# Generated by Django 5.0.4 on 2024-04-10 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0010_alter_emprestimo_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 2, 31, 38, 567729)),
        ),
    ]
