# Generated by Django 5.0.4 on 2024-04-10 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0012_alter_emprestimo_valor_alter_emprestimo_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocompraevendaacoes',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 17, 40, 35, 539609)),
        ),
    ]
