# Generated by Django 5.0.4 on 2024-04-11 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0015_agencia_user_user_is_agencia_user_is_gerentepf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 21, 1, 29, 727260)),
        ),
    ]
