# Generated by Django 5.0.4 on 2024-04-11 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0016_alter_emprestimo_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 21, 9, 40, 17423)),
        ),
    ]
