# Generated by Django 5.0.4 on 2024-04-11 01:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0017_alter_emprestimo_vencimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Agencia',
            new_name='is_agencia',
        ),
        migrations.AddField(
            model_name='gerentepf',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gerentepj',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 22, 27, 0, 327713)),
        ),
    ]
