# Generated by Django 5.0.4 on 2024-04-11 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0018_rename_is_agencia_user_is_agencia_gerentepf_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gerentePJ',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 23, 33, 28, 967169)),
        ),
    ]
