# Generated by Django 5.0.4 on 2024-04-11 03:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0019_user_is_gerentepj_alter_emprestimo_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtb.agencia'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtb.agencia'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 0, 57, 53, 705185)),
        ),
    ]
