# Generated by Django 5.0.4 on 2024-04-11 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtb', '0020_pessoafisica_agencia_pessoajuridica_agencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='dias_ate_vencimento',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 0, 59, 3, 252690)),
        ),
    ]
